import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script type="text/javascript" src="/nes.min.js"></script>
      </head>
      <body className={inter.className}>
        <div className="z-10 max-w-5xl relative flex-row w-full items-center justify-between font-mono text-sm lg:flex">
          <div className="fixed left-0 top-0 flex w-full min-w-80 justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit">
            <Link href="/">
              <div className="fixed left-1 top-[-20px]  flex z-10">
                <Image
                  className="dark:drop-shadow-[0_0_0.3rem_#ffffff70]"
                  src="/devhat.png"
                  alt="Next.js Logo"
                  width={110}
                  height={25}
                  priority
                />
              </div>
              <code className="font-mono font-bold">
                HatTalk/webview by brunocroh
              </code>
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
